apiVersion: v1
kind: Service
metadata:
  name: azure-vote-service
  namespace: {{ .Values.namespace }}
  labels:
    app: azure-vote
spec:
  type: {{ .Values.service.type }}
  selector:
    app: azure-vote
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

